"""Add new column world to Question

Revision ID: 751b138b7ace
Revises: 922c4fd907b6
Create Date: 2025-06-07 18:49:42.097170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751b138b7ace'
down_revision = '922c4fd907b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('world', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subcategory', sa.String(length=100), nullable=True))
        batch_op.drop_column('mundo')
        batch_op.drop_column('subcategoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mundo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('subcategory')
        batch_op.drop_column('world')

    # ### end Alembic commands ###
