"""empty message

Revision ID: 922c4fd907b6
Revises: c52662fb5d7b
Create Date: 2025-06-07 18:35:52.602702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922c4fd907b6'
down_revision = 'c52662fb5d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mundo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subcategoria', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('subcategoria')
        batch_op.drop_column('mundo')

    # ### end Alembic commands ###
